version: "3.9"

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "${REST_PORT}:${REST_PORT}"
      - "${EXTERNAL_GRPC_HOST}:${EXTERNAL_GRPC_HOST}"
      - "${INTERNAL_GRPC_HOST}:${INTERNAL_GRPC_HOST}"
    environment:
      EXTERNAL_GRPC_HOST: ${EXTERNAL_GRPC_HOST}
      INTERNAL_GRPC_HOST: ${INTERNAL_GRPC_HOST}
      REST_PORT: ${REST_PORT}
      HEALTHCHECK_PORT: ${HEALTHCHECK_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:${HEALTHCHECK_PORT}/status || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5

  envoy:
    build:
      context: ./envoy
      dockerfile: envoy.Dockerfile
    restart: unless-stopped
    ports:
      - "9000:9000"
    links:
      - app
    depends_on:
      - app
