// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: spoon/auth/api.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResponse_LoginResponseError_LoginResponseErrorType int32

const (
	LoginResponse_LoginResponseError_UNSPECIFIED LoginResponse_LoginResponseError_LoginResponseErrorType = 0
	LoginResponse_LoginResponseError_BAD_REQUEST LoginResponse_LoginResponseError_LoginResponseErrorType = 1
)

// Enum value maps for LoginResponse_LoginResponseError_LoginResponseErrorType.
var (
	LoginResponse_LoginResponseError_LoginResponseErrorType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BAD_REQUEST",
	}
	LoginResponse_LoginResponseError_LoginResponseErrorType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"BAD_REQUEST": 1,
	}
)

func (x LoginResponse_LoginResponseError_LoginResponseErrorType) Enum() *LoginResponse_LoginResponseError_LoginResponseErrorType {
	p := new(LoginResponse_LoginResponseError_LoginResponseErrorType)
	*p = x
	return p
}

func (x LoginResponse_LoginResponseError_LoginResponseErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResponse_LoginResponseError_LoginResponseErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spoon_auth_api_proto_enumTypes[0].Descriptor()
}

func (LoginResponse_LoginResponseError_LoginResponseErrorType) Type() protoreflect.EnumType {
	return &file_spoon_auth_api_proto_enumTypes[0]
}

func (x LoginResponse_LoginResponseError_LoginResponseErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResponse_LoginResponseError_LoginResponseErrorType.Descriptor instead.
func (LoginResponse_LoginResponseError_LoginResponseErrorType) EnumDescriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{1, 0, 0}
}

type RefreshResponse_LoginResponseError_LoginResponseErrorType int32

const (
	RefreshResponse_LoginResponseError_UNSPECIFIED RefreshResponse_LoginResponseError_LoginResponseErrorType = 0
	RefreshResponse_LoginResponseError_BAD_REQUEST RefreshResponse_LoginResponseError_LoginResponseErrorType = 1
)

// Enum value maps for RefreshResponse_LoginResponseError_LoginResponseErrorType.
var (
	RefreshResponse_LoginResponseError_LoginResponseErrorType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BAD_REQUEST",
	}
	RefreshResponse_LoginResponseError_LoginResponseErrorType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"BAD_REQUEST": 1,
	}
)

func (x RefreshResponse_LoginResponseError_LoginResponseErrorType) Enum() *RefreshResponse_LoginResponseError_LoginResponseErrorType {
	p := new(RefreshResponse_LoginResponseError_LoginResponseErrorType)
	*p = x
	return p
}

func (x RefreshResponse_LoginResponseError_LoginResponseErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefreshResponse_LoginResponseError_LoginResponseErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spoon_auth_api_proto_enumTypes[1].Descriptor()
}

func (RefreshResponse_LoginResponseError_LoginResponseErrorType) Type() protoreflect.EnumType {
	return &file_spoon_auth_api_proto_enumTypes[1]
}

func (x RefreshResponse_LoginResponseError_LoginResponseErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefreshResponse_LoginResponseError_LoginResponseErrorType.Descriptor instead.
func (RefreshResponse_LoginResponseError_LoginResponseErrorType) EnumDescriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{3, 0, 0}
}

type CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType int32

const (
	CreateUserResponse_CreateUserResponseError_UNSPECIFIED CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType = 0
	CreateUserResponse_CreateUserResponseError_BAD_REQUEST CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType = 1
)

// Enum value maps for CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType.
var (
	CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BAD_REQUEST",
	}
	CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"BAD_REQUEST": 1,
	}
)

func (x CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType) Enum() *CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType {
	p := new(CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType)
	*p = x
	return p
}

func (x CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spoon_auth_api_proto_enumTypes[2].Descriptor()
}

func (CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType) Type() protoreflect.EnumType {
	return &file_spoon_auth_api_proto_enumTypes[2]
}

func (x CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType.Descriptor instead.
func (CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType) EnumDescriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{5, 0, 0}
}

type UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType int32

const (
	UpdateUserResponse_UpdateUserResponseError_UNSPECIFIED     UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType = 0
	UpdateUserResponse_UpdateUserResponseError_BAD_REQUEST     UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType = 1
	UpdateUserResponse_UpdateUserResponseError_UNAUTHENTICATED UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType = 2
	UpdateUserResponse_UpdateUserResponseError_UNAUTHORIZED    UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType = 3
)

// Enum value maps for UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType.
var (
	UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BAD_REQUEST",
		2: "UNAUTHENTICATED",
		3: "UNAUTHORIZED",
	}
	UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType_value = map[string]int32{
		"UNSPECIFIED":     0,
		"BAD_REQUEST":     1,
		"UNAUTHENTICATED": 2,
		"UNAUTHORIZED":    3,
	}
)

func (x UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType) Enum() *UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType {
	p := new(UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType)
	*p = x
	return p
}

func (x UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spoon_auth_api_proto_enumTypes[3].Descriptor()
}

func (UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType) Type() protoreflect.EnumType {
	return &file_spoon_auth_api_proto_enumTypes[3]
}

func (x UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType.Descriptor instead.
func (UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType) EnumDescriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{7, 0, 0}
}

type DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType int32

const (
	DeleteUserResponse_DeleteUserResponseError_UNSPECIFIED     DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType = 0
	DeleteUserResponse_DeleteUserResponseError_BAD_REQUEST     DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType = 1
	DeleteUserResponse_DeleteUserResponseError_UNAUTHENTICATED DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType = 2
	DeleteUserResponse_DeleteUserResponseError_UNAUTHORIZED    DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType = 3
)

// Enum value maps for DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType.
var (
	DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "BAD_REQUEST",
		2: "UNAUTHENTICATED",
		3: "UNAUTHORIZED",
	}
	DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType_value = map[string]int32{
		"UNSPECIFIED":     0,
		"BAD_REQUEST":     1,
		"UNAUTHENTICATED": 2,
		"UNAUTHORIZED":    3,
	}
)

func (x DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType) Enum() *DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType {
	p := new(DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType)
	*p = x
	return p
}

func (x DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spoon_auth_api_proto_enumTypes[4].Descriptor()
}

func (DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType) Type() protoreflect.EnumType {
	return &file_spoon_auth_api_proto_enumTypes[4]
}

func (x DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType.Descriptor instead.
func (DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType) EnumDescriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{9, 0, 0}
}

type GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType int32

const (
	GetPublicKeyResponse_GetPublicKeyResponseError_UNSPECIFIED GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType = 0
)

// Enum value maps for GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType.
var (
	GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType_name = map[int32]string{
		0: "UNSPECIFIED",
	}
	GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType_value = map[string]int32{
		"UNSPECIFIED": 0,
	}
)

func (x GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType) Enum() *GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType {
	p := new(GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType)
	*p = x
	return p
}

func (x GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_spoon_auth_api_proto_enumTypes[5].Descriptor()
}

func (GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType) Type() protoreflect.EnumType {
	return &file_spoon_auth_api_proto_enumTypes[5]
}

func (x GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType.Descriptor instead.
func (GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType) EnumDescriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{11, 0, 0}
}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginId  string `protobuf:"bytes,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*LoginResponse_ResponseError
	//	*LoginResponse_ResponseBody
	Response isLoginResponse_Response `protobuf_oneof:"response"`
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{1}
}

func (m *LoginResponse) GetResponse() isLoginResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *LoginResponse) GetResponseError() *LoginResponse_LoginResponseError {
	if x, ok := x.GetResponse().(*LoginResponse_ResponseError); ok {
		return x.ResponseError
	}
	return nil
}

func (x *LoginResponse) GetResponseBody() *LoginResponse_LoginResponseBody {
	if x, ok := x.GetResponse().(*LoginResponse_ResponseBody); ok {
		return x.ResponseBody
	}
	return nil
}

type isLoginResponse_Response interface {
	isLoginResponse_Response()
}

type LoginResponse_ResponseError struct {
	ResponseError *LoginResponse_LoginResponseError `protobuf:"bytes,1,opt,name=response_error,json=responseError,proto3,oneof"`
}

type LoginResponse_ResponseBody struct {
	ResponseBody *LoginResponse_LoginResponseBody `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3,oneof"`
}

func (*LoginResponse_ResponseError) isLoginResponse_Response() {}

func (*LoginResponse_ResponseBody) isLoginResponse_Response() {}

type RefreshRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefreshToken *JWT `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshRequest) GetRefreshToken() *JWT {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type RefreshResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*RefreshResponse_ResponseError
	//	*RefreshResponse_ResponseBody
	Response isRefreshResponse_Response `protobuf_oneof:"response"`
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{3}
}

func (m *RefreshResponse) GetResponse() isRefreshResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *RefreshResponse) GetResponseError() *RefreshResponse_LoginResponseError {
	if x, ok := x.GetResponse().(*RefreshResponse_ResponseError); ok {
		return x.ResponseError
	}
	return nil
}

func (x *RefreshResponse) GetResponseBody() *RefreshResponse_LoginResponseBody {
	if x, ok := x.GetResponse().(*RefreshResponse_ResponseBody); ok {
		return x.ResponseBody
	}
	return nil
}

type isRefreshResponse_Response interface {
	isRefreshResponse_Response()
}

type RefreshResponse_ResponseError struct {
	ResponseError *RefreshResponse_LoginResponseError `protobuf:"bytes,1,opt,name=response_error,json=responseError,proto3,oneof"`
}

type RefreshResponse_ResponseBody struct {
	ResponseBody *RefreshResponse_LoginResponseBody `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3,oneof"`
}

func (*RefreshResponse_ResponseError) isRefreshResponse_Response() {}

func (*RefreshResponse_ResponseBody) isRefreshResponse_Response() {}

type CreateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginId  string  `protobuf:"bytes,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	Password string  `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email    *string `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetLoginId() string {
	if x != nil {
		return x.LoginId
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*CreateUserResponse_ResponseError
	//	*CreateUserResponse_ResponseBody
	Response isCreateUserResponse_Response `protobuf_oneof:"response"`
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{5}
}

func (m *CreateUserResponse) GetResponse() isCreateUserResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CreateUserResponse) GetResponseError() *CreateUserResponse_CreateUserResponseError {
	if x, ok := x.GetResponse().(*CreateUserResponse_ResponseError); ok {
		return x.ResponseError
	}
	return nil
}

func (x *CreateUserResponse) GetResponseBody() *CreateUserResponse_CreateUserResponseBody {
	if x, ok := x.GetResponse().(*CreateUserResponse_ResponseBody); ok {
		return x.ResponseBody
	}
	return nil
}

type isCreateUserResponse_Response interface {
	isCreateUserResponse_Response()
}

type CreateUserResponse_ResponseError struct {
	ResponseError *CreateUserResponse_CreateUserResponseError `protobuf:"bytes,1,opt,name=response_error,json=responseError,proto3,oneof"`
}

type CreateUserResponse_ResponseBody struct {
	ResponseBody *CreateUserResponse_CreateUserResponseBody `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3,oneof"`
}

func (*CreateUserResponse_ResponseError) isCreateUserResponse_Response() {}

func (*CreateUserResponse_ResponseBody) isCreateUserResponse_Response() {}

type UpdateUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*UpdateUserResponse_ResponseError
	//	*UpdateUserResponse_ResponseBody
	Response isUpdateUserResponse_Response `protobuf_oneof:"response"`
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{7}
}

func (m *UpdateUserResponse) GetResponse() isUpdateUserResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *UpdateUserResponse) GetResponseError() *UpdateUserResponse_UpdateUserResponseError {
	if x, ok := x.GetResponse().(*UpdateUserResponse_ResponseError); ok {
		return x.ResponseError
	}
	return nil
}

func (x *UpdateUserResponse) GetResponseBody() *UpdateUserResponse_UpdateUserResponseBody {
	if x, ok := x.GetResponse().(*UpdateUserResponse_ResponseBody); ok {
		return x.ResponseBody
	}
	return nil
}

type isUpdateUserResponse_Response interface {
	isUpdateUserResponse_Response()
}

type UpdateUserResponse_ResponseError struct {
	ResponseError *UpdateUserResponse_UpdateUserResponseError `protobuf:"bytes,1,opt,name=response_error,json=responseError,proto3,oneof"`
}

type UpdateUserResponse_ResponseBody struct {
	ResponseBody *UpdateUserResponse_UpdateUserResponseBody `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3,oneof"`
}

func (*UpdateUserResponse_ResponseError) isUpdateUserResponse_Response() {}

func (*UpdateUserResponse_ResponseBody) isUpdateUserResponse_Response() {}

type DeleteUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*DeleteUserResponse_ResponseError
	//	*DeleteUserResponse_ResponseBody
	Response isDeleteUserResponse_Response `protobuf_oneof:"response"`
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{9}
}

func (m *DeleteUserResponse) GetResponse() isDeleteUserResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *DeleteUserResponse) GetResponseError() *DeleteUserResponse_DeleteUserResponseError {
	if x, ok := x.GetResponse().(*DeleteUserResponse_ResponseError); ok {
		return x.ResponseError
	}
	return nil
}

func (x *DeleteUserResponse) GetResponseBody() *DeleteUserResponse_DeleteUserResponseBody {
	if x, ok := x.GetResponse().(*DeleteUserResponse_ResponseBody); ok {
		return x.ResponseBody
	}
	return nil
}

type isDeleteUserResponse_Response interface {
	isDeleteUserResponse_Response()
}

type DeleteUserResponse_ResponseError struct {
	ResponseError *DeleteUserResponse_DeleteUserResponseError `protobuf:"bytes,1,opt,name=response_error,json=responseError,proto3,oneof"`
}

type DeleteUserResponse_ResponseBody struct {
	ResponseBody *DeleteUserResponse_DeleteUserResponseBody `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3,oneof"`
}

func (*DeleteUserResponse_ResponseError) isDeleteUserResponse_Response() {}

func (*DeleteUserResponse_ResponseBody) isDeleteUserResponse_Response() {}

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{10}
}

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*GetPublicKeyResponse_ResponseError
	//	*GetPublicKeyResponse_ResponseBody
	Response isGetPublicKeyResponse_Response `protobuf_oneof:"response"`
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{11}
}

func (m *GetPublicKeyResponse) GetResponse() isGetPublicKeyResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *GetPublicKeyResponse) GetResponseError() *GetPublicKeyResponse_GetPublicKeyResponseError {
	if x, ok := x.GetResponse().(*GetPublicKeyResponse_ResponseError); ok {
		return x.ResponseError
	}
	return nil
}

func (x *GetPublicKeyResponse) GetResponseBody() *GetPublicKeyResponse_GetPublicKeyResponseBody {
	if x, ok := x.GetResponse().(*GetPublicKeyResponse_ResponseBody); ok {
		return x.ResponseBody
	}
	return nil
}

type isGetPublicKeyResponse_Response interface {
	isGetPublicKeyResponse_Response()
}

type GetPublicKeyResponse_ResponseError struct {
	ResponseError *GetPublicKeyResponse_GetPublicKeyResponseError `protobuf:"bytes,1,opt,name=response_error,json=responseError,proto3,oneof"`
}

type GetPublicKeyResponse_ResponseBody struct {
	ResponseBody *GetPublicKeyResponse_GetPublicKeyResponseBody `protobuf:"bytes,2,opt,name=response_body,json=responseBody,proto3,oneof"`
}

func (*GetPublicKeyResponse_ResponseError) isGetPublicKeyResponse_Response() {}

func (*GetPublicKeyResponse_ResponseBody) isGetPublicKeyResponse_Response() {}

type LoginResponse_LoginResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string                                                 `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Type    LoginResponse_LoginResponseError_LoginResponseErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.LoginResponse_LoginResponseError_LoginResponseErrorType" json:"type,omitempty"`
}

func (x *LoginResponse_LoginResponseError) Reset() {
	*x = LoginResponse_LoginResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_LoginResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_LoginResponseError) ProtoMessage() {}

func (x *LoginResponse_LoginResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_LoginResponseError.ProtoReflect.Descriptor instead.
func (*LoginResponse_LoginResponseError) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *LoginResponse_LoginResponseError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *LoginResponse_LoginResponseError) GetType() LoginResponse_LoginResponseError_LoginResponseErrorType {
	if x != nil {
		return x.Type
	}
	return LoginResponse_LoginResponseError_UNSPECIFIED
}

type LoginResponse_LoginResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  *JWT `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken *JWT `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *LoginResponse_LoginResponseBody) Reset() {
	*x = LoginResponse_LoginResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse_LoginResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse_LoginResponseBody) ProtoMessage() {}

func (x *LoginResponse_LoginResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse_LoginResponseBody.ProtoReflect.Descriptor instead.
func (*LoginResponse_LoginResponseBody) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *LoginResponse_LoginResponseBody) GetAccessToken() *JWT {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *LoginResponse_LoginResponseBody) GetRefreshToken() *JWT {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type RefreshResponse_LoginResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string                                                   `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Type    RefreshResponse_LoginResponseError_LoginResponseErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.RefreshResponse_LoginResponseError_LoginResponseErrorType" json:"type,omitempty"`
}

func (x *RefreshResponse_LoginResponseError) Reset() {
	*x = RefreshResponse_LoginResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshResponse_LoginResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse_LoginResponseError) ProtoMessage() {}

func (x *RefreshResponse_LoginResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse_LoginResponseError.ProtoReflect.Descriptor instead.
func (*RefreshResponse_LoginResponseError) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *RefreshResponse_LoginResponseError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *RefreshResponse_LoginResponseError) GetType() RefreshResponse_LoginResponseError_LoginResponseErrorType {
	if x != nil {
		return x.Type
	}
	return RefreshResponse_LoginResponseError_UNSPECIFIED
}

type RefreshResponse_LoginResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken  *JWT `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken *JWT `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
}

func (x *RefreshResponse_LoginResponseBody) Reset() {
	*x = RefreshResponse_LoginResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshResponse_LoginResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse_LoginResponseBody) ProtoMessage() {}

func (x *RefreshResponse_LoginResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse_LoginResponseBody.ProtoReflect.Descriptor instead.
func (*RefreshResponse_LoginResponseBody) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{3, 1}
}

func (x *RefreshResponse_LoginResponseBody) GetAccessToken() *JWT {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *RefreshResponse_LoginResponseBody) GetRefreshToken() *JWT {
	if x != nil {
		return x.RefreshToken
	}
	return nil
}

type CreateUserResponse_CreateUserResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string                                                                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Type    CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType" json:"type,omitempty"`
}

func (x *CreateUserResponse_CreateUserResponseError) Reset() {
	*x = CreateUserResponse_CreateUserResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse_CreateUserResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse_CreateUserResponseError) ProtoMessage() {}

func (x *CreateUserResponse_CreateUserResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse_CreateUserResponseError.ProtoReflect.Descriptor instead.
func (*CreateUserResponse_CreateUserResponseError) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *CreateUserResponse_CreateUserResponseError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *CreateUserResponse_CreateUserResponseError) GetType() CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType {
	if x != nil {
		return x.Type
	}
	return CreateUserResponse_CreateUserResponseError_UNSPECIFIED
}

type CreateUserResponse_CreateUserResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *CreateUserResponse_CreateUserResponseBody) Reset() {
	*x = CreateUserResponse_CreateUserResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserResponse_CreateUserResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse_CreateUserResponseBody) ProtoMessage() {}

func (x *CreateUserResponse_CreateUserResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse_CreateUserResponseBody.ProtoReflect.Descriptor instead.
func (*CreateUserResponse_CreateUserResponseBody) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{5, 1}
}

func (x *CreateUserResponse_CreateUserResponseBody) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse_UpdateUserResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string                                                                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Type    UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType" json:"type,omitempty"`
}

func (x *UpdateUserResponse_UpdateUserResponseError) Reset() {
	*x = UpdateUserResponse_UpdateUserResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserResponse_UpdateUserResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse_UpdateUserResponseError) ProtoMessage() {}

func (x *UpdateUserResponse_UpdateUserResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse_UpdateUserResponseError.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse_UpdateUserResponseError) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{7, 0}
}

func (x *UpdateUserResponse_UpdateUserResponseError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *UpdateUserResponse_UpdateUserResponseError) GetType() UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType {
	if x != nil {
		return x.Type
	}
	return UpdateUserResponse_UpdateUserResponseError_UNSPECIFIED
}

type UpdateUserResponse_UpdateUserResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UpdateUserResponse_UpdateUserResponseBody) Reset() {
	*x = UpdateUserResponse_UpdateUserResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserResponse_UpdateUserResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse_UpdateUserResponseBody) ProtoMessage() {}

func (x *UpdateUserResponse_UpdateUserResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse_UpdateUserResponseBody.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse_UpdateUserResponseBody) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{7, 1}
}

func (x *UpdateUserResponse_UpdateUserResponseBody) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserResponse_DeleteUserResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string                                                                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Type    DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType" json:"type,omitempty"`
}

func (x *DeleteUserResponse_DeleteUserResponseError) Reset() {
	*x = DeleteUserResponse_DeleteUserResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserResponse_DeleteUserResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse_DeleteUserResponseError) ProtoMessage() {}

func (x *DeleteUserResponse_DeleteUserResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse_DeleteUserResponseError.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse_DeleteUserResponseError) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{9, 0}
}

func (x *DeleteUserResponse_DeleteUserResponseError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *DeleteUserResponse_DeleteUserResponseError) GetType() DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType {
	if x != nil {
		return x.Type
	}
	return DeleteUserResponse_DeleteUserResponseError_UNSPECIFIED
}

type DeleteUserResponse_DeleteUserResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteUserResponse_DeleteUserResponseBody) Reset() {
	*x = DeleteUserResponse_DeleteUserResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserResponse_DeleteUserResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse_DeleteUserResponseBody) ProtoMessage() {}

func (x *DeleteUserResponse_DeleteUserResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse_DeleteUserResponseBody.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse_DeleteUserResponseBody) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{9, 1}
}

type GetPublicKeyResponse_GetPublicKeyResponseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *string                                                                      `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	Type    GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=auth.GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType" json:"type,omitempty"`
}

func (x *GetPublicKeyResponse_GetPublicKeyResponseError) Reset() {
	*x = GetPublicKeyResponse_GetPublicKeyResponseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicKeyResponse_GetPublicKeyResponseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse_GetPublicKeyResponseError) ProtoMessage() {}

func (x *GetPublicKeyResponse_GetPublicKeyResponseError) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse_GetPublicKeyResponseError.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse_GetPublicKeyResponseError) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetPublicKeyResponse_GetPublicKeyResponseError) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

func (x *GetPublicKeyResponse_GetPublicKeyResponseError) GetType() GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType {
	if x != nil {
		return x.Type
	}
	return GetPublicKeyResponse_GetPublicKeyResponseError_UNSPECIFIED
}

type GetPublicKeyResponse_GetPublicKeyResponseBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *GetPublicKeyResponse_GetPublicKeyResponseBody) Reset() {
	*x = GetPublicKeyResponse_GetPublicKeyResponseBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_spoon_auth_api_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPublicKeyResponse_GetPublicKeyResponseBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse_GetPublicKeyResponseBody) ProtoMessage() {}

func (x *GetPublicKeyResponse_GetPublicKeyResponseBody) ProtoReflect() protoreflect.Message {
	mi := &file_spoon_auth_api_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse_GetPublicKeyResponseBody.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse_GetPublicKeyResponseBody) Descriptor() ([]byte, []int) {
	return file_spoon_auth_api_proto_rawDescGZIP(), []int{11, 1}
}

func (x *GetPublicKeyResponse_GetPublicKeyResponseBody) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_spoon_auth_api_proto protoreflect.FileDescriptor

var file_spoon_auth_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x70, 0x6f, 0x6f, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x75, 0x74, 0x68, 0x1a, 0x16, 0x73, 0x70,
	0x6f, 0x6f, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x70, 0x6f, 0x6f, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x0c, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x22, 0xfe, 0x03, 0x0a, 0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4c, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x6f, 0x64, 0x79, 0x1a, 0xce, 0x01, 0x0a, 0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x51, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3d, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x16,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52,
	0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x71, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x2c, 0x0a, 0x0c, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x57, 0x54, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4a, 0x57, 0x54, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x40, 0x0a, 0x0e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x4a, 0x57, 0x54, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x86, 0x04, 0x0a, 0x0f, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x0e, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x28, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0d, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4e, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x0c,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0xd0, 0x01, 0x0a,
	0x12, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x53, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x3f, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x10, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a,
	0x71, 0x0a, 0x11, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x6f, 0x64, 0x79, 0x12, 0x2c, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x4a, 0x57, 0x54, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x2e, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x4a, 0x57, 0x54, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6f,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0xf7, 0x03, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x00, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x56, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0xe7, 0x01, 0x0a, 0x17, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x88, 0x01, 0x01, 0x12, 0x60, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x4c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3f, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45,
	0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x1a, 0x38, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x0a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x33, 0x0a, 0x11, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x9e,
	0x04, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48,
	0x00, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x56, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x8e, 0x02, 0x0a, 0x17, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x88, 0x01, 0x01, 0x12, 0x60, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x4c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x66, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51,
	0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48,
	0x45, 0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x55,
	0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x03, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x38, 0x0a, 0x16, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x6f, 0x64, 0x79, 0x12, 0x1e, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2c, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xfe, 0x03,
	0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x61,
	0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x56, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0x8e, 0x02, 0x0a, 0x17, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x88,
	0x01, 0x01, 0x12, 0x60, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x4c, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x66, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x41, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55,
	0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x45,
	0x4e, 0x54, 0x49, 0x43, 0x41, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e,
	0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x5a, 0x45, 0x44, 0x10, 0x03, 0x42, 0x0a, 0x0a, 0x08,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f,
	0x64, 0x79, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xfb, 0x03, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d,
	0x0a, 0x0e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65,
	0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0d,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x5a, 0x0a,
	0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x1a, 0xe0, 0x01, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x88, 0x01, 0x01, 0x12, 0x66, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x52, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x30,
	0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x39, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x88, 0x01, 0x0a, 0x1c, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x12, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73,
	0x68, 0x12, 0x14, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe4,
	0x01, 0x0a, 0x1f, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x12, 0x17, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x63, 0x0a, 0x1a, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x64, 0x69, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x2d, 0x63, 0x65, 0x6c, 0x65, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x73, 0x70, 0x6f, 0x6f, 0x6e, 0x2f, 0x73, 0x70, 0x6f,
	0x6f, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x3b, 0x61, 0x75, 0x74, 0x68, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_spoon_auth_api_proto_rawDescOnce sync.Once
	file_spoon_auth_api_proto_rawDescData = file_spoon_auth_api_proto_rawDesc
)

func file_spoon_auth_api_proto_rawDescGZIP() []byte {
	file_spoon_auth_api_proto_rawDescOnce.Do(func() {
		file_spoon_auth_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_spoon_auth_api_proto_rawDescData)
	})
	return file_spoon_auth_api_proto_rawDescData
}

var file_spoon_auth_api_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_spoon_auth_api_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_spoon_auth_api_proto_goTypes = []interface{}{
	(LoginResponse_LoginResponseError_LoginResponseErrorType)(0),                      // 0: auth.LoginResponse.LoginResponseError.LoginResponseErrorType
	(RefreshResponse_LoginResponseError_LoginResponseErrorType)(0),                    // 1: auth.RefreshResponse.LoginResponseError.LoginResponseErrorType
	(CreateUserResponse_CreateUserResponseError_CreateUserResponseErrorType)(0),       // 2: auth.CreateUserResponse.CreateUserResponseError.CreateUserResponseErrorType
	(UpdateUserResponse_UpdateUserResponseError_UpdateUserResponseErrorType)(0),       // 3: auth.UpdateUserResponse.UpdateUserResponseError.UpdateUserResponseErrorType
	(DeleteUserResponse_DeleteUserResponseError_DeleteUserResponseErrorType)(0),       // 4: auth.DeleteUserResponse.DeleteUserResponseError.DeleteUserResponseErrorType
	(GetPublicKeyResponse_GetPublicKeyResponseError_GetPublicKeyResponseErrorType)(0), // 5: auth.GetPublicKeyResponse.GetPublicKeyResponseError.GetPublicKeyResponseErrorType
	(*LoginRequest)(nil),                                   // 6: auth.LoginRequest
	(*LoginResponse)(nil),                                  // 7: auth.LoginResponse
	(*RefreshRequest)(nil),                                 // 8: auth.RefreshRequest
	(*RefreshResponse)(nil),                                // 9: auth.RefreshResponse
	(*CreateUserRequest)(nil),                              // 10: auth.CreateUserRequest
	(*CreateUserResponse)(nil),                             // 11: auth.CreateUserResponse
	(*UpdateUserRequest)(nil),                              // 12: auth.UpdateUserRequest
	(*UpdateUserResponse)(nil),                             // 13: auth.UpdateUserResponse
	(*DeleteUserRequest)(nil),                              // 14: auth.DeleteUserRequest
	(*DeleteUserResponse)(nil),                             // 15: auth.DeleteUserResponse
	(*GetPublicKeyRequest)(nil),                            // 16: auth.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil),                           // 17: auth.GetPublicKeyResponse
	(*LoginResponse_LoginResponseError)(nil),               // 18: auth.LoginResponse.LoginResponseError
	(*LoginResponse_LoginResponseBody)(nil),                // 19: auth.LoginResponse.LoginResponseBody
	(*RefreshResponse_LoginResponseError)(nil),             // 20: auth.RefreshResponse.LoginResponseError
	(*RefreshResponse_LoginResponseBody)(nil),              // 21: auth.RefreshResponse.LoginResponseBody
	(*CreateUserResponse_CreateUserResponseError)(nil),     // 22: auth.CreateUserResponse.CreateUserResponseError
	(*CreateUserResponse_CreateUserResponseBody)(nil),      // 23: auth.CreateUserResponse.CreateUserResponseBody
	(*UpdateUserResponse_UpdateUserResponseError)(nil),     // 24: auth.UpdateUserResponse.UpdateUserResponseError
	(*UpdateUserResponse_UpdateUserResponseBody)(nil),      // 25: auth.UpdateUserResponse.UpdateUserResponseBody
	(*DeleteUserResponse_DeleteUserResponseError)(nil),     // 26: auth.DeleteUserResponse.DeleteUserResponseError
	(*DeleteUserResponse_DeleteUserResponseBody)(nil),      // 27: auth.DeleteUserResponse.DeleteUserResponseBody
	(*GetPublicKeyResponse_GetPublicKeyResponseError)(nil), // 28: auth.GetPublicKeyResponse.GetPublicKeyResponseError
	(*GetPublicKeyResponse_GetPublicKeyResponseBody)(nil),  // 29: auth.GetPublicKeyResponse.GetPublicKeyResponseBody
	(*JWT)(nil),  // 30: auth.JWT
	(*User)(nil), // 31: auth.User
}
var file_spoon_auth_api_proto_depIdxs = []int32{
	18, // 0: auth.LoginResponse.response_error:type_name -> auth.LoginResponse.LoginResponseError
	19, // 1: auth.LoginResponse.response_body:type_name -> auth.LoginResponse.LoginResponseBody
	30, // 2: auth.RefreshRequest.refresh_token:type_name -> auth.JWT
	20, // 3: auth.RefreshResponse.response_error:type_name -> auth.RefreshResponse.LoginResponseError
	21, // 4: auth.RefreshResponse.response_body:type_name -> auth.RefreshResponse.LoginResponseBody
	22, // 5: auth.CreateUserResponse.response_error:type_name -> auth.CreateUserResponse.CreateUserResponseError
	23, // 6: auth.CreateUserResponse.response_body:type_name -> auth.CreateUserResponse.CreateUserResponseBody
	31, // 7: auth.UpdateUserRequest.user:type_name -> auth.User
	24, // 8: auth.UpdateUserResponse.response_error:type_name -> auth.UpdateUserResponse.UpdateUserResponseError
	25, // 9: auth.UpdateUserResponse.response_body:type_name -> auth.UpdateUserResponse.UpdateUserResponseBody
	26, // 10: auth.DeleteUserResponse.response_error:type_name -> auth.DeleteUserResponse.DeleteUserResponseError
	27, // 11: auth.DeleteUserResponse.response_body:type_name -> auth.DeleteUserResponse.DeleteUserResponseBody
	28, // 12: auth.GetPublicKeyResponse.response_error:type_name -> auth.GetPublicKeyResponse.GetPublicKeyResponseError
	29, // 13: auth.GetPublicKeyResponse.response_body:type_name -> auth.GetPublicKeyResponse.GetPublicKeyResponseBody
	0,  // 14: auth.LoginResponse.LoginResponseError.type:type_name -> auth.LoginResponse.LoginResponseError.LoginResponseErrorType
	30, // 15: auth.LoginResponse.LoginResponseBody.access_token:type_name -> auth.JWT
	30, // 16: auth.LoginResponse.LoginResponseBody.refresh_token:type_name -> auth.JWT
	1,  // 17: auth.RefreshResponse.LoginResponseError.type:type_name -> auth.RefreshResponse.LoginResponseError.LoginResponseErrorType
	30, // 18: auth.RefreshResponse.LoginResponseBody.access_token:type_name -> auth.JWT
	30, // 19: auth.RefreshResponse.LoginResponseBody.refresh_token:type_name -> auth.JWT
	2,  // 20: auth.CreateUserResponse.CreateUserResponseError.type:type_name -> auth.CreateUserResponse.CreateUserResponseError.CreateUserResponseErrorType
	31, // 21: auth.CreateUserResponse.CreateUserResponseBody.user:type_name -> auth.User
	3,  // 22: auth.UpdateUserResponse.UpdateUserResponseError.type:type_name -> auth.UpdateUserResponse.UpdateUserResponseError.UpdateUserResponseErrorType
	31, // 23: auth.UpdateUserResponse.UpdateUserResponseBody.user:type_name -> auth.User
	4,  // 24: auth.DeleteUserResponse.DeleteUserResponseError.type:type_name -> auth.DeleteUserResponse.DeleteUserResponseError.DeleteUserResponseErrorType
	5,  // 25: auth.GetPublicKeyResponse.GetPublicKeyResponseError.type:type_name -> auth.GetPublicKeyResponse.GetPublicKeyResponseError.GetPublicKeyResponseErrorType
	6,  // 26: auth.AuthenticationSessionService.Login:input_type -> auth.LoginRequest
	8,  // 27: auth.AuthenticationSessionService.Refresh:input_type -> auth.RefreshRequest
	10, // 28: auth.AuthenticationManagementService.CreateUser:input_type -> auth.CreateUserRequest
	12, // 29: auth.AuthenticationManagementService.UpdateUser:input_type -> auth.UpdateUserRequest
	14, // 30: auth.AuthenticationManagementService.DeleteUser:input_type -> auth.DeleteUserRequest
	16, // 31: auth.AuthenticationAuditService.GetPublicKey:input_type -> auth.GetPublicKeyRequest
	7,  // 32: auth.AuthenticationSessionService.Login:output_type -> auth.LoginResponse
	9,  // 33: auth.AuthenticationSessionService.Refresh:output_type -> auth.RefreshResponse
	11, // 34: auth.AuthenticationManagementService.CreateUser:output_type -> auth.CreateUserResponse
	13, // 35: auth.AuthenticationManagementService.UpdateUser:output_type -> auth.UpdateUserResponse
	15, // 36: auth.AuthenticationManagementService.DeleteUser:output_type -> auth.DeleteUserResponse
	17, // 37: auth.AuthenticationAuditService.GetPublicKey:output_type -> auth.GetPublicKeyResponse
	32, // [32:38] is the sub-list for method output_type
	26, // [26:32] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_spoon_auth_api_proto_init() }
func file_spoon_auth_api_proto_init() {
	if File_spoon_auth_api_proto != nil {
		return
	}
	file_spoon_auth_token_proto_init()
	file_spoon_auth_user_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_spoon_auth_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_LoginResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse_LoginResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshResponse_LoginResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshResponse_LoginResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse_CreateUserResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserResponse_CreateUserResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserResponse_UpdateUserResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserResponse_UpdateUserResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserResponse_DeleteUserResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserResponse_DeleteUserResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyResponse_GetPublicKeyResponseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_spoon_auth_api_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyResponse_GetPublicKeyResponseBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_spoon_auth_api_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*LoginResponse_ResponseError)(nil),
		(*LoginResponse_ResponseBody)(nil),
	}
	file_spoon_auth_api_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*RefreshResponse_ResponseError)(nil),
		(*RefreshResponse_ResponseBody)(nil),
	}
	file_spoon_auth_api_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_spoon_auth_api_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*CreateUserResponse_ResponseError)(nil),
		(*CreateUserResponse_ResponseBody)(nil),
	}
	file_spoon_auth_api_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*UpdateUserResponse_ResponseError)(nil),
		(*UpdateUserResponse_ResponseBody)(nil),
	}
	file_spoon_auth_api_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*DeleteUserResponse_ResponseError)(nil),
		(*DeleteUserResponse_ResponseBody)(nil),
	}
	file_spoon_auth_api_proto_msgTypes[11].OneofWrappers = []interface{}{
		(*GetPublicKeyResponse_ResponseError)(nil),
		(*GetPublicKeyResponse_ResponseBody)(nil),
	}
	file_spoon_auth_api_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_spoon_auth_api_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_spoon_auth_api_proto_msgTypes[16].OneofWrappers = []interface{}{}
	file_spoon_auth_api_proto_msgTypes[18].OneofWrappers = []interface{}{}
	file_spoon_auth_api_proto_msgTypes[20].OneofWrappers = []interface{}{}
	file_spoon_auth_api_proto_msgTypes[22].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_spoon_auth_api_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_spoon_auth_api_proto_goTypes,
		DependencyIndexes: file_spoon_auth_api_proto_depIdxs,
		EnumInfos:         file_spoon_auth_api_proto_enumTypes,
		MessageInfos:      file_spoon_auth_api_proto_msgTypes,
	}.Build()
	File_spoon_auth_api_proto = out.File
	file_spoon_auth_api_proto_rawDesc = nil
	file_spoon_auth_api_proto_goTypes = nil
	file_spoon_auth_api_proto_depIdxs = nil
}
